# this docker compose pulls images
services:
  psg:
    image: postgres:17
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgs-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  auth-service:
    image: mos1ck/q-post-auth-service:latest
    container_name: auth-service
    env_file:
      - .env
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    depends_on:
      - psg

  user-service:
    image: mos1ck/q-post-user-service:latest
    container_name: user-service
    env_file:
      - .env
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      - psg

  auth-migrate:
    image: mos1ck/q-post-auth-migrate:latest
    env_file:
      - .env
    depends_on:
      - psg

  user-migrate:
    image: mos1ck/q-post-user-migrate:latest
    env_file:
      - .env
    depends_on:
      - psg

volumes:
  pgs-data: